### ISSUE TITLE
[enhancement]: speed up (forced) snapshot refresh

### ISSUE THREAD

**Issue by thieren** [homebridge-plugins/homebridge-eufy-security#33]
### Describe the solution you'd like

I think the `forcerefreshsnap` option was introduced to control regular updates of the snapshot view.
However there is a little drawback I've encountered:

When the camera detects an event (motion, person, doorbell, ...) the eufy client automatically pushes the new pictureUrl. This then is not used when the `forcerefreshsnap` option is enabled.
A consequence of this is that the image for the push notification from HomeKit is delayed by the time it needs to start the livestream and render the snapshot for the notification.

I think a better way would be to keep track of how old the pushed picture url is and use this instead for the notifications as long as it is recent enough. I would suggest 5 seconds.

Will try to realize this in a few days.

**Comment by schliemann** [comment]
@thieren I think your reasoning is correct. However I'm interested in knowing what snapshot you are seeing when just receiving it from the doorbell pressed push. On my end it is always the previous event - not the current one.

**Comment by thieren** [comment]
@schliemann I think that depends on the configuration you're using. In my case I use `forcerefreshsnap` and so the occuring SnapshotRequest loads the livestream and gets one frame from the camera.

But I have an assumption as to why you're seeing the last event instead:
I noticed that when the doorbell is triggered a new `pictureURL`is generated from eufy cloud. However this URL is not valid until eufy itself started the camera and takes a snapshot. So in the handleSnapshot method the ffmpeg process can't utilize this url because there has not elapsed enough time yet for the eufy cloud to keep up.
But I'm a bit confused as to why the old snapshot is used. The way I understand it, there would be no snapshot (due to no valid pictureURL). Maybe there is some caching from HomeKit itself.

Do you have `forcerefreshsnap` disabled and also don't trigger motion events? This would at least explain why you always seem to see only old snapshots from doorbell events.


I'm currently working on a SnapshotManager that tries to circumvent some of these problems. Mainly it shall give back a snapshot as fast as possible.
As stated above the behavior that a snapshot takes a few seconds to process has major disadvantages in my view.
For example if I open HomeKit and almost immediately open the camera stream it will only start after the snapshot request is fulfilled that was started beforehand. This can in total take up to 10 seconds in my case. In my opinion this is too much for a good user experience.

**Comment by schliemann** [comment]
@thieren Makes sense. I have disabled motion detection on my doorbell to preserve battery.

How does your night vision snapshots look? In the old repo I got snapshots with night vision working by adding "-ss 00:00:00.500" to ffmpeg. Without it I get a completely black snapshot.

**Comment by thieren** [comment]
@schliemann It's the same with the night vision snapshots for me. I think that's a limitation from the hardware design side of the eufy devices. The camera probably detects whether to use night vision by analyzing the brightness of the video (just an assumption) And so the first frames always will be dark until the device turns on night vision.

**Comment by schliemann** [comment]
No. The problem is that we pick the first frame for the snapshot. The first frame never utilizes night vision. That's why the seek fixes it.

**Comment by thieren** [comment]
Yeah that is what I meant or rather what would be the consequence of my assumption.
I'm totally with you. I too don't think that the first frame ever utilizes the night vision. As for why exactly this is, is not absolutely clear.
Anyway, since we have no other choice at the moment a workaround as described by you is the best alternative I think.

**Comment by schliemann** [comment]
@thieren Ah. I probably misunderstood your previous post. Sorry.

Also regarding the current doorbell pressed functionality this is what I see if forcedrefresh is disabled.

On iphone:
Doorbell pressed event with old snapshot unrelated to the current doorbell event.

On AppleTv:
AppleTv shows a PIP Doorbell pressed event with old snapshot unrelated to the current doorbell event.
AppleTV shows a PIP live feed which is live

**Comment by lenoxys** [comment]
hey, 2 cents, I think Eufy App is cheating and keep is own snap cache and force to generate one when user is opening the app.

**Comment by schliemann** [comment]
@lenoxys @bropat Something is definitely going on. But I presume the android app is able to show the correct snapshot on push? And the eufy security client is built on the android app. So it is a bit odd that the snapshot is not the current one.

**Comment by thieren** [comment]
Hi

Added this in 2.0.1-beta.6

@schliemann Could you check if your problem with the old snapshot on ring events is solved by this?

Also please let me know what you think of this change.

Basically there is a new section in the camera configuration wizard with three options for snapshot handling.
'Force new snapshots' works mostly like `forcesnaprefresh` and 'speed' acts like the normal behavior with a few improvements to both.
The 'balanced' option tries to combine the two to get fewer outdated snapshots but also don't generate too much delay in the snapshot generating process.

Additionally there are a few extra options:

- generate a snapshot automatically every x minutes
- delay a camera snapshot by 0.5 seconds (as mentioned by @schliemann to improve night vision snaps)
- setting to speed up notifications on doorbell ring events

**Comment by schliemann** [comment]
@thieren Looks very interesting. Looking forward to test this. Not home until tuesday however.

**Comment by fullphat** [comment]
Currently using Balanced mode without any specific periodic refresh.  Will continue to test but it seems to be working well.

**Comment by fullphat** [comment]
Update: set a 5 minute refresh but this morning logs are saying "livestream didn't start in time" so it seems the snapshot hasn't updated since midnight.  It usually takes 7-8 seconds for a snapshot to create - any way we can configure the timeout duration?

**Comment by thieren** [comment]
> Update: set a 5 minute refresh but this morning logs are saying "livestream didn't start in time" so it seems the snapshot hasn't updated since midnight. It usually takes 7-8 seconds for a snapshot to create - any way we can configure the timeout duration?

Hey @fullphat 

can you provide a longer log output with detailed logging enabled?
Also I'd need your json config.

The current timeout is 15 seconds. So in theory should be way enough.

**Comment by thieren** [comment]
Hi @all

Just released a revised beta with a few small fixes/improvements to the snapshot handling.

@fullphat I believe this should fix the problem with the automatic refresh. Let me know if it's doing it's job now.

**Comment by fullphat** [comment]
Will take a look!  I noticed earlier that the plugin had stopped and wouldn't restart.  In the end I had to kill the process with Activity Monitor and it came back ok.  I don't have the logs but if it happens again I'll try to save them off.

**Comment by fullphat** [comment]
Just given it a try.  I got an error saying no snapshot in memory but it then still times-out when creating a snapshot.  

I gave it 5 minutes but it didn't seem to create a snapshot and when I launched the Home app again, I got the same "No snapshot" error in the log but this time it didn't try to create one.

![image](https://user-images.githubusercontent.com/11242840/172065263-01c44e54-cd88-4caa-b415-62085eb386ff.jpeg)

**Comment by thieren** [comment]
Hi @fullphat 

can't quite follow you. For a few other people it's working at least. So I'll need a longer log output and also your json config.

But before that please try to empty your browser cache and save the settings via config wizard again. Unfortunately this seems to be the source of some strange bugs. (see #1 for reference)

**Comment by schliemann** [comment]
@thieren Do I have to have forcesnaprefresh specified if I use the new snapshotHandlingMethod?

**Comment by thieren** [comment]
> @thieren Do I have to have forcesnaprefresh specified if I use the new snapshotHandlingMethod?

Hey @schliemann no forcesnaprefresh will not be used with the new snapshot handling

ok not entirely true. If the new handling is enabled but no method defined aka. Balanced forced, speed the plug-in will determine the method based on forcesnaprefresh
But that's only because the new handling is enabled by default and I needed a way to determine which method works best for the individual user.
If you configure the thing via config ui the old option is ignored entirely.

**Comment by thieren** [comment]
Is implemented with release of 2.1.0
